package raw

// PCAN 通道句柄。与 PCANBasic.h 中的 PCAN_USBBUS*/PCAN_PCIBUS*/PCAN_LANBUS* 对齐。
const (
	PCAN_NONEBUS TPCANHandle = 0x00 // 未定义通道

	// PCAN-USB：1..16
	PCAN_USBBUS1  TPCANHandle = 0x51
	PCAN_USBBUS2  TPCANHandle = 0x52
	PCAN_USBBUS3  TPCANHandle = 0x53
	PCAN_USBBUS4  TPCANHandle = 0x54
	PCAN_USBBUS5  TPCANHandle = 0x55
	PCAN_USBBUS6  TPCANHandle = 0x56
	PCAN_USBBUS7  TPCANHandle = 0x57
	PCAN_USBBUS8  TPCANHandle = 0x58
	PCAN_USBBUS9  TPCANHandle = 0x509
	PCAN_USBBUS10 TPCANHandle = 0x50A
	PCAN_USBBUS11 TPCANHandle = 0x50B
	PCAN_USBBUS12 TPCANHandle = 0x50C
	PCAN_USBBUS13 TPCANHandle = 0x50D
	PCAN_USBBUS14 TPCANHandle = 0x50E
	PCAN_USBBUS15 TPCANHandle = 0x50F
	PCAN_USBBUS16 TPCANHandle = 0x510

	// PCAN-PCI：1..16
	PCAN_PCIBUS1  TPCANHandle = 0x41
	PCAN_PCIBUS2  TPCANHandle = 0x42
	PCAN_PCIBUS3  TPCANHandle = 0x43
	PCAN_PCIBUS4  TPCANHandle = 0x44
	PCAN_PCIBUS5  TPCANHandle = 0x45
	PCAN_PCIBUS6  TPCANHandle = 0x46
	PCAN_PCIBUS7  TPCANHandle = 0x47
	PCAN_PCIBUS8  TPCANHandle = 0x48
	PCAN_PCIBUS9  TPCANHandle = 0x409
	PCAN_PCIBUS10 TPCANHandle = 0x40A
	PCAN_PCIBUS11 TPCANHandle = 0x40B
	PCAN_PCIBUS12 TPCANHandle = 0x40C
	PCAN_PCIBUS13 TPCANHandle = 0x40D
	PCAN_PCIBUS14 TPCANHandle = 0x40E
	PCAN_PCIBUS15 TPCANHandle = 0x40F
	PCAN_PCIBUS16 TPCANHandle = 0x410

	// PCAN-LAN：1..16
	PCAN_LANBUS1  TPCANHandle = 0x801
	PCAN_LANBUS2  TPCANHandle = 0x802
	PCAN_LANBUS3  TPCANHandle = 0x803
	PCAN_LANBUS4  TPCANHandle = 0x804
	PCAN_LANBUS5  TPCANHandle = 0x805
	PCAN_LANBUS6  TPCANHandle = 0x806
	PCAN_LANBUS7  TPCANHandle = 0x807
	PCAN_LANBUS8  TPCANHandle = 0x808
	PCAN_LANBUS9  TPCANHandle = 0x809
	PCAN_LANBUS10 TPCANHandle = 0x80A
	PCAN_LANBUS11 TPCANHandle = 0x80B
	PCAN_LANBUS12 TPCANHandle = 0x80C
	PCAN_LANBUS13 TPCANHandle = 0x80D
	PCAN_LANBUS14 TPCANHandle = 0x80E
	PCAN_LANBUS15 TPCANHandle = 0x80F
	PCAN_LANBUS16 TPCANHandle = 0x810
)

// Classical CAN 波特率常量。
// 这些是 BTR0/BTR1 编码值，与 PCANBasic.h 一致。
const (
	PCAN_BAUD_1M   TPCANBaudrate = 0x0014
	PCAN_BAUD_800K TPCANBaudrate = 0x0016
	PCAN_BAUD_500K TPCANBaudrate = 0x001C
	PCAN_BAUD_250K TPCANBaudrate = 0x011C
	PCAN_BAUD_125K TPCANBaudrate = 0x031C
	PCAN_BAUD_100K TPCANBaudrate = 0x432F
	PCAN_BAUD_95K  TPCANBaudrate = 0xC34E
	PCAN_BAUD_83K  TPCANBaudrate = 0x852B
	PCAN_BAUD_50K  TPCANBaudrate = 0x472F
	PCAN_BAUD_47K  TPCANBaudrate = 0x1414
	PCAN_BAUD_33K  TPCANBaudrate = 0x8B2F
	PCAN_BAUD_20K  TPCANBaudrate = 0x532F
	PCAN_BAUD_10K  TPCANBaudrate = 0x672F
	PCAN_BAUD_5K   TPCANBaudrate = 0x7F7F
)

// 错误码（位掩码语义）。
// PCAN 错误可以是多个位的 OR 组合，例如 BUSOFF|QOVERRUN。
const (
	PCAN_ERROR_OK         TPCANStatus = 0x00000 // 没有错误
	PCAN_ERROR_XMTFULL    TPCANStatus = 0x00001 // 发送缓冲区满
	PCAN_ERROR_OVERRUN    TPCANStatus = 0x00002 // CAN 控制器溢出
	PCAN_ERROR_BUSLIGHT   TPCANStatus = 0x00004 // 总线错误计数 light
	PCAN_ERROR_BUSHEAVY   TPCANStatus = 0x00008 // 总线错误计数 heavy
	PCAN_ERROR_BUSWARNING TPCANStatus = 0x00008 // 总线警告（PCAN 中与 BUSHEAVY 同值）
	PCAN_ERROR_BUSPASSIVE TPCANStatus = 0x40000 // 节点进入 passive 错误状态
	PCAN_ERROR_BUSOFF     TPCANStatus = 0x00010 // 总线已断开

	// 任一总线错误位，便于做"任意总线异常"判断。
	PCAN_ERROR_ANYBUSERR TPCANStatus = PCAN_ERROR_BUSWARNING | PCAN_ERROR_BUSLIGHT |
		PCAN_ERROR_BUSHEAVY | PCAN_ERROR_BUSOFF | PCAN_ERROR_BUSPASSIVE

	PCAN_ERROR_QRCVEMPTY    TPCANStatus = 0x00020 // 接收队列空（Read 时常见）
	PCAN_ERROR_QOVERRUN     TPCANStatus = 0x00040 // 接收队列被覆盖（应用读取过慢）
	PCAN_ERROR_QXMTFULL     TPCANStatus = 0x00080 // 发送队列满
	PCAN_ERROR_REGTEST      TPCANStatus = 0x00100 // 自检失败
	PCAN_ERROR_NODRIVER     TPCANStatus = 0x00200 // 驱动未加载
	PCAN_ERROR_HWINUSE      TPCANStatus = 0x00400 // 硬件已被其他网络使用
	PCAN_ERROR_NETINUSE     TPCANStatus = 0x00800 // 客户端已连接此网络
	PCAN_ERROR_ILLHW        TPCANStatus = 0x01400 // 非法硬件句柄
	PCAN_ERROR_ILLNET       TPCANStatus = 0x01800 // 非法网络句柄
	PCAN_ERROR_ILLCLIENT    TPCANStatus = 0x01C00 // 非法客户端句柄
	PCAN_ERROR_ILLHANDLE    TPCANStatus = PCAN_ERROR_ILLHW | PCAN_ERROR_ILLNET | PCAN_ERROR_ILLCLIENT
	PCAN_ERROR_RESOURCE     TPCANStatus = 0x02000   // 资源不足
	PCAN_ERROR_ILLPARAMTYPE TPCANStatus = 0x04000   // 非法参数类型
	PCAN_ERROR_ILLPARAMVAL  TPCANStatus = 0x08000   // 非法参数值
	PCAN_ERROR_UNKNOWN      TPCANStatus = 0x10000   // 未知错误
	PCAN_ERROR_ILLDATA      TPCANStatus = 0x20000   // 非法数据
	PCAN_ERROR_ILLOPERATION TPCANStatus = 0x80000   // 非法操作（如不支持此功能）
	PCAN_ERROR_INITIALIZE   TPCANStatus = 0x4000000 // 通道未被初始化
)

// 帧类型位。可按 OR 组合（如 FD|BRS|EXTENDED）。
const (
	PCAN_MESSAGE_STANDARD TPCANMessageType = 0x00 // 11 位 ID 数据帧
	PCAN_MESSAGE_RTR      TPCANMessageType = 0x01 // 远程请求帧
	PCAN_MESSAGE_EXTENDED TPCANMessageType = 0x02 // 29 位 ID
	PCAN_MESSAGE_FD       TPCANMessageType = 0x04 // CAN FD 帧
	PCAN_MESSAGE_BRS      TPCANMessageType = 0x08 // FD 加速段开关
	PCAN_MESSAGE_ESI      TPCANMessageType = 0x10 // FD 错误状态指示
	PCAN_MESSAGE_ECHO     TPCANMessageType = 0x20 // 自发送回环
	PCAN_MESSAGE_ERRFRAME TPCANMessageType = 0x40 // 错误帧
	PCAN_MESSAGE_STATUS   TPCANMessageType = 0x80 // 状态信息帧
)

// SetValue/GetValue 用到的参数。v0.1 仅列出实际用到的。
const (
	PCAN_DEVICE_NUMBER       TPCANParameter = 0x01
	PCAN_5VOLTS_POWER        TPCANParameter = 0x02
	PCAN_RECEIVE_EVENT       TPCANParameter = 0x03
	PCAN_MESSAGE_FILTER      TPCANParameter = 0x04
	PCAN_API_VERSION         TPCANParameter = 0x05
	PCAN_CHANNEL_VERSION     TPCANParameter = 0x06
	PCAN_BUSOFF_AUTORESET    TPCANParameter = 0x07
	PCAN_LISTEN_ONLY         TPCANParameter = 0x08
	PCAN_LOG_LOCATION        TPCANParameter = 0x09
	PCAN_LOG_STATUS          TPCANParameter = 0x0A
	PCAN_LOG_CONFIGURE       TPCANParameter = 0x0B
	PCAN_LOG_TEXT            TPCANParameter = 0x0C
	PCAN_CHANNEL_CONDITION   TPCANParameter = 0x0D
	PCAN_HARDWARE_NAME       TPCANParameter = 0x0E
	PCAN_RECEIVE_STATUS      TPCANParameter = 0x0F
	PCAN_CONTROLLER_NUMBER   TPCANParameter = 0x10
	PCAN_TRACE_LOCATION      TPCANParameter = 0x11
	PCAN_TRACE_STATUS        TPCANParameter = 0x12
	PCAN_TRACE_SIZE          TPCANParameter = 0x13
	PCAN_TRACE_CONFIGURE     TPCANParameter = 0x14
	PCAN_CHANNEL_IDENTIFYING TPCANParameter = 0x15
	PCAN_CHANNEL_FEATURES    TPCANParameter = 0x16
	PCAN_BITRATE_ADAPTING    TPCANParameter = 0x17
	PCAN_BITRATE_INFO        TPCANParameter = 0x18
	PCAN_BITRATE_INFO_FD     TPCANParameter = 0x19
	PCAN_BUSSPEED_NOMINAL    TPCANParameter = 0x1A
	PCAN_BUSSPEED_DATA       TPCANParameter = 0x1B
	PCAN_IP_ADDRESS          TPCANParameter = 0x1C
	PCAN_LAN_SERVICE_STATUS  TPCANParameter = 0x1D
	PCAN_ALLOW_STATUS_FRAMES TPCANParameter = 0x1E
	PCAN_ALLOW_RTR_FRAMES    TPCANParameter = 0x1F
	PCAN_ALLOW_ERROR_FRAMES  TPCANParameter = 0x20
)

// 过滤器模式：用于 SetValue(PCAN_MESSAGE_FILTER, ...) 的 value。
const (
	PCAN_FILTER_CLOSE  TPCANParameter = 0x00 // 关闭滤波器（不接收任何帧）
	PCAN_FILTER_OPEN   TPCANParameter = 0x01 // 打开滤波器（接收所有帧）
	PCAN_FILTER_CUSTOM TPCANParameter = 0x02 // 自定义（通过 FilterMessages 设置）
)

// GetErrorText 的语言代码。
const (
	LanguageNeutral uint16 = 0x00
	LanguageEnglish uint16 = 0x09
	LanguageGerman  uint16 = 0x07
	LanguageSpanish uint16 = 0x0A
	LanguageItalian uint16 = 0x10
	LanguageFrench  uint16 = 0x0C
)
